### ISSUE TITLE
Pass a directory as a parameter

### ISSUE THREAD

**Issue by Boggin** [rickardn/Consolas#3]
I have used Consolas to create a console app. It requires a path to a directory to be passed as an argument. This fails as it sees the ':' (colon) as an Operator in the path 'C:\first\second\folder'. I've also tried relative paths. 

The problem seems to be in the `ArgumentLL2Parser` class but I'm unsure about how to prevent the `Tokens.Operator.IsMatch` from checking inside my path string.

Example: 

```
C:\> MyConsolasApp.exe "C:\path\to\folder\" 
```

```
Unhandled Exception: System.Exception: Couldn't parse ':' as value
   at Consolas.Core.ArgumentLL2Parser.GetValue() in C:\Source\github\Consolas\Source\ConsoleApp.Core\ArgumentLL2Parser.cs:line 90
```

**Comment by FrikkinLazer** [comment]
Same problem. Should I escape the : character somehow?
