### ISSUE TITLE
Provide Required Attribute and Async return

### ISSUE THREAD

**Issue by NiklasRaab** [rickardn/Consolas#9]
If i mark a property with [Required] the Console should be asking about them.

And how can i write data to console during executing command? Building a tree who is renderd partly?

**Comment by rickardn** [comment]
1. how would you want to be asked about a property? Can you elaborate?

**Comment by rickardn** [comment]
2. you can allways use System.Console.WriteLine directly however you can also import IConsole in the command constructor. You get a wrapper around System.Console which you can mock out in your unit tests

**Comment by NiklasRaab** [comment]
Ok thanks, for response. I'm using your Framework as following:

```
while(true){
var input = Console.ReadLine();
Match(input.Split(' '))
}
```

Then you can ask for a property.

Second:
I've found out now that you can use WriteLine, but this breaks the pattern of "MVC" and the code is less unittestable.

**Comment by rickardn** [comment]
Ok, I see.  The framework has not been design for interactivity yet. It's on the roadmap.
The way you're using it might work but was never the intention.

Here is a code sample of how to use Console.WriteLine in a unit testable mannor:

```
class Program : ConsoleApp<Program>
{
	static void Main(string[] args)
	{
		Match(args);
	}

	public override void Configure(SimpleInjector.Container container)
	{
		container.Register<IConsole, SystemConsole>();
	}
}
```


```
public class Defaultcommand : Command 
{
	private IConsole _console;
	public DefaultCommand(IConsole console)
	{
		_console = console;
	}

	public object Execute(DefaultArgs args)
	{
		_console.WriteLine("foo bar");

		...
	}
}
```
